"""add weight to User table

Revision ID: 21ae785964f6
Revises: d96ed8b95196
Create Date: 2026-04-29 11:03:55.197729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21ae785964f6'
down_revision: Union[str, Sequence[str], None] = 'd96ed8b95196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('User', 'height',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('User', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('User', 'height',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('User', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
