"""change id' name

Revision ID: 82bbbb3e33aa
Revises: 
Create Date: 2026-04-29 15:00:46.389622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bbbb3e33aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.String(length=510), nullable=False),
    sa.Column('exercise_types', sa.Enum('REPS', 'Time', name='settype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Exercise_id'), 'Exercise', ['id'], unique=False)
    op.create_table('Muscle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Muscle_id'), 'Muscle', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('height', sa.Float(precision=5, asdecimal=2), nullable=False),
    sa.Column('weight', sa.Float(precision=5, asdecimal=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('ExerciseMuscle',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['Muscle.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('Workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Workout_id'), 'Workout', ['id'], unique=False)
    op.create_table('WorkoutExercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WorkoutExercise_id'), 'WorkoutExercise', ['id'], unique=False)
    op.create_table('ExerciseSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['WorkoutExercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExerciseSet_id'), 'ExerciseSet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ExerciseSet_id'), table_name='ExerciseSet')
    op.drop_table('ExerciseSet')
    op.drop_index(op.f('ix_WorkoutExercise_id'), table_name='WorkoutExercise')
    op.drop_table('WorkoutExercise')
    op.drop_index(op.f('ix_Workout_id'), table_name='Workout')
    op.drop_table('Workout')
    op.drop_table('ExerciseMuscle')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Muscle_id'), table_name='Muscle')
    op.drop_table('Muscle')
    op.drop_index(op.f('ix_Exercise_id'), table_name='Exercise')
    op.drop_table('Exercise')
    # ### end Alembic commands ###
