"""add User table

Revision ID: 8f897208dcc9
Revises: 51c53e2e62b5
Create Date: 2026-04-28 13:41:37.486377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f897208dcc9'
down_revision: Union[str, Sequence[str], None] = '51c53e2e62b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Float(precision=5, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
