"""add all db tabels

Revision ID: 914b2cf9e5be
Revises: 21ae785964f6
Create Date: 2026-04-29 11:19:37.465653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914b2cf9e5be'
down_revision: Union[str, Sequence[str], None] = '21ae785964f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.String(length=510), nullable=False),
    sa.Column('exercise_types', sa.Enum('REPS', 'Time', name='settype'), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_index(op.f('ix_Exercise_exercise_id'), 'Exercise', ['exercise_id'], unique=False)
    op.create_table('Muscle',
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('muscle_id')
    )
    op.create_index(op.f('ix_Muscle_muscle_id'), 'Muscle', ['muscle_id'], unique=False)
    op.create_table('ExerciseMuscle',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['Muscle.muscle_id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('Workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_index(op.f('ix_Workout_workout_id'), 'Workout', ['workout_id'], unique=False)
    op.create_table('WorkoutExercise',
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.workout_id'], ),
    sa.PrimaryKeyConstraint('workout_exercise_id')
    )
    op.create_index(op.f('ix_WorkoutExercise_workout_exercise_id'), 'WorkoutExercise', ['workout_exercise_id'], unique=False)
    op.create_table('ExerciseSet',
    sa.Column('exercise_set_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['WorkoutExercise.workout_exercise_id'], ),
    sa.PrimaryKeyConstraint('exercise_set_id')
    )
    op.create_index(op.f('ix_ExerciseSet_exercise_set_id'), 'ExerciseSet', ['exercise_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ExerciseSet_exercise_set_id'), table_name='ExerciseSet')
    op.drop_table('ExerciseSet')
    op.drop_index(op.f('ix_WorkoutExercise_workout_exercise_id'), table_name='WorkoutExercise')
    op.drop_table('WorkoutExercise')
    op.drop_index(op.f('ix_Workout_workout_id'), table_name='Workout')
    op.drop_table('Workout')
    op.drop_table('ExerciseMuscle')
    op.drop_index(op.f('ix_Muscle_muscle_id'), table_name='Muscle')
    op.drop_table('Muscle')
    op.drop_index(op.f('ix_Exercise_exercise_id'), table_name='Exercise')
    op.drop_table('Exercise')
    # ### end Alembic commands ###
