"""add weight to User table

Revision ID: d96ed8b95196
Revises: 8f897208dcc9
Create Date: 2026-04-28 13:45:08.026367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96ed8b95196'
down_revision: Union[str, Sequence[str], None] = '8f897208dcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('weight', sa.Float(precision=5, asdecimal=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'weight')
    # ### end Alembic commands ###
