"""add target rows to WorkoutExercise table

Revision ID: ea4e8e88e6d3
Revises: 18f0242551a3
Create Date: 2026-04-29 16:01:23.823861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4e8e88e6d3'
down_revision: Union[str, Sequence[str], None] = '18f0242551a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WorkoutExercise', sa.Column('target_sets', sa.Integer(), nullable=False))
    op.add_column('WorkoutExercise', sa.Column('target_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WorkoutExercise', 'target_duration')
    op.drop_column('WorkoutExercise', 'target_sets')
    # ### end Alembic commands ###
